project:
  type: website

website:
  title: "Open Data Public Measures Toolkit"
  page-navigation: true
  back-to-top-navigation: true
  
  navbar:
    background: primary
    search: true
    reader-mode: true
    left:
      - text: Home
        href: index.qmd
      - text: Action Measures
        href: actions.qmd
      - text: Data Portal Measures
        href: data_portal_measures.qmd
      - text: Engagement Measures
        href: engagement.qmd
      - reporting.qmd
      - about.qmd
  page-footer:
      background: light
      left: "Copyright 2026, Alicia Brown" 
      right: 
        - icon: github
          href: https://github.com/aliciatb/open-data-action-toolkit

format:
  html:
    respect-user-color-scheme: true
    theme:
      - pulse
      - brand
    css: styles.css
    toc: true
    table:
      striped: true
      hover: true

editor: visual

