project:
  type: website

website:
  title: "Open Data Public Measures Toolkit"
  page-navigation: true
  back-to-top-navigation: true
  
  navbar:
    background: primary
    search: true
    reader-mode: true
    left:
      - text: Home
        href: index.qmd
      - text: Actions
        menu:
          - actions.qmd
          - text: Data Products
            href: data_products.qmd
          - text: Policy & Standards
            href: policy_standards.qmd
      - text: Data Portal Measures
        menu: 
          - data_portal_measures.qmd
          - text: Web Analytics
            href: analytics.qmd
          - text: Catalog Quality
            href: catalog_measures.qmd
      - text: Engagement
        menu: 
          - engagement.qmd
          - text: Articles
            href: articles.qmd
          - text: Public Activity
            href: public_activity.qmd
      - text: Reporting
        menu:
          - reporting.qmd
          - text: Measures Catalog
            href: measures.qmd
      - text: Practical Applications
        href: act_now.qmd
      - text: About
        href: about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/aliciatb/open-data-action-toolkit
          - text: Report an Issue
            href: https://github.com/aliciatb/open-data-action-toolkit/issues/new/choose
  page-footer:
      background: light
      left: "Copyright 2026, Alicia Brown" 
      right: 
        - icon: github
          href: https://github.com/aliciatb/open-data-action-toolkit

format:
  html:
    respect-user-color-scheme: true
    theme:
      - pulse
      - brand
    css: styles.css
    toc: true

editor: visual

