---
title: "Organizational Actions"
bibliography: references.bib
link-citations: true
---

Actions taken to support the use of open data provide indications of commitment by organizations to users.

## Data Products

The creation of new datasets may represent the fulfillment of public requests [@mergel2018] or signify successful collaboration with departments to publish data that demonstrates their work on behalf of the public [@johnson2016].

Datasets can be measured by their value to departments and the public. Dataset characteristics like category, agency function, expected user group, information type, and related open government principle have been used to evaluate the public usefulness of a data catalog [@schwoerer2022]. The evaluation of metadata completion, communication mechanisms, and publishing frequency provides a way to track the commitment of a program to providing open data [@nahon2015].

## Support

Providing users access through support platforms makes it easy to isolate and report open data requests for help, new data, and detailed public information queries. Requests made by the public are valuable opportunities to gather feedback and build trust by responding to matters that are meaningful and personally important to members of the public [@guy2021].

Online content, communication channels, tutorials, videos, and case studies that enable users are actions that should be reported as organizational action measures.

## Events

Open data day celebrations, datathons, and hackathons are ways that open data programs, departments, community organizations, researchers, local news organizations, and technology sponsors typically engage the public to participate in a day, weekend, or week of using government data to help understand and tackle important community issues.

In addition to counting the number of events and attendees, there are other measures that show the contributions made by the public. Examples of important hackathon measures include new ideas, viable design concepts, prototypes, participant social connections, new start-ups, and increased domain and technical knowledge gains for participants [@jaskiewicz2019].

## Policy and Standards

- Council resolutions

- Executive directives

- Recommendations

- Legal mandates

- Budget support

- Technology standards

## 
